config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root to: 'news#list'
  
  get 'static_pages/index'

  resources :services
  resources :news
  resources :payments

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '*tail' => "static_pages#index"
end

app/models/news.rb
# == Schema Information
#
# Table name: news
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :string(255)
#  body        :text(65535)
#  main_page   :boolean          default(FALSE)
#  published   :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string(255)
#

class News < ApplicationRecord
  include Slugable
  
  # Relations
  has_many :pictures, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true

  # Validations
  validates :title, :description, :body, presence: true
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show, :list]
  before_action :find_news, only: [:show, :edit, :update, :delete, :destroy]
  layout "blog", only: [:index, :show]

  def index
    @news = News.all.where(published: true).order(id: :desc)
  end

  def list
    @news = News.all.where(published: true).order(id: :desc).limit(4)
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    if @news.save
      redirect_to @news
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @news.update(update_params)
      redirect_to @news
    else
      render :edit
    end
  end

  def delete
  end

  def destroy
    @news.destroy
    redirect_to @news
  end

  def update_params; news_params end

  private

    def news_params
      params.require(:news).permit(:title, :description, :body, :main_page, :published, :slug, pictures_attributes: [:id, :file, :_destroy])
    end

    def find_news
      @news = News.find(params[:id])
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.slim
- @news.each do |n|
  h3 = link_to n.title, news_path(n.to_param)
  - n.pictures.each do |p|
    .picture
      = image_tag p.file_url.to_s
  .date
      p = I18n.l n.created_at, format: :long
  .body
    = n.description.html_safe

app/views/news/list.html.slim
- @news.each do |n|
  .date 
    = I18n.l n.created_at, format: :long
  h5
    = link_to n.title, news_path(n.to_param)
  .picture
    - n.pictures.each do |p|
      = image_tag p.file_url.to_s
  hr

app/views/news/show.html.slim
h3 = @news.title
- @news.pictures.each do |p|
  .picture
    = image_tag p.file_url.to_s
.date
  p = I18n.l @news.created_at, format: :long
.body
  = @news.body.html_safe