config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root to: 'news#list'
  
  get 'static_pages/index'

  resources :services
  resources :news
  resources :payments

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '*tail' => "static_pages#index"
end

app/views/layouts/_callout.html.slim
.container
  .row
    .col-lg-9
      h3
        | Хотите подключиться? Нет ничего проще!
      p
        | Чтобы начать, просто нажмите на кнопку
    .col-lg-3
      = link_to "Подать заявку", "#", class: "btn btn-default btn-lg"

app/views/layouts/_footer.html.slim
.container
  .row
    .col-lg-12
      p © ООО Крыминфоком 1996 - #{Time.now.year} гг.

app/views/layouts/_header.html.slim
.navbar.navbar-default.navbar-fixed-top role="navigation" 
  .container
    .navbar-header
      button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Крыминфоком", root_path, class: "navbar-brand"
    .navbar-collapse.collapse.navbar-right
      ul.nav.navbar-nav
        li
          = link_to "Новости", news_index_path, class: current_page?(news_index_path) && 'active'
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            | О компании
            b.caret
          ul.dropdown-menu.active
            - StaticPage.all.limit(4).each do |sp|
              li = link_to sp.title, "/#{sp.slug}", class: current_page?("/#{sp.slug}") && 'active' 
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#" 
            | Услуги и цены
            b.caret
          ul.dropdown-menu.active
            - Service.all.each do |s| 
              li = link_to s.name, service_path(s.to_param)
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            | Оплата
            b.caret
          ul.dropdown-menu.active
            - Payment.all.each do |pay|
              li = link_to pay.title, payment_path(pay.to_param) 
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#" 
            | Для клиентов
            b.caret
          ul.dropdown-menu.active
            li = link_to "Личный кабинет", "http://billing.crimeainfo.com/"
        - StaticPage.where(id: 6).each do |sp|
          li= link_to sp.title, "/#{sp.slug}", class: current_page?("/#{sp.slug}") && 'active'
        - StaticPage.where(id: 5).each do |sp|
          li= link_to sp.title, "/#{sp.slug}", class: current_page?("/#{sp.slug}") && 'active'

app/views/layouts/_hover.html.slim
#carousel-example-generic.carousel.slide data-ride="carousel" 
  ol.carousel-indicators
    li.active data-slide-to="0" data-target="#carousel-example-generic" 
    li data-slide-to="1" data-target="#carousel-example-generic" 
    li data-slide-to="2" data-target="#carousel-example-generic" 
  .carousel-inner role="listbox" 
    .item.active
      .container
        .row
          .col-lg-6
            = image_tag('girl_table.png')
          .col-lg-6
            .box
              h1 Беспроводной доступ
              p
                | Предлагаем вам воспользоваться новыми услугами от «Крымнфоком» - беспроводной доступ по технологии AirMax 5G.
              p
                = link_to "Подробнее", service_path(1), class: "btn btn-next"
      .carousel-caption
    .item
      .container
        .row
          .col-lg-6
            .box
              h1 Выделенная линия
              p
                | Подключение к сети Интернет по выделенным линиям наиболее эффективно для компаний, чья деятельность связана с необходимостью постоянного присутствия во всемирной сети.
              p
                = link_to "Подробнее", service_path(2), class: "btn btn-next"
          .col-lg-6
            = image_tag('man.png')
      .carousel-caption
  a.left.carousel-control data-slide="prev" href="#carousel-example-generic" role="button" 
    span.glyphicon.glyphicon-chevron-left aria-hidden="true" 
    span.sr-only Previous
  a.right.carousel-control data-slide="next" href="#carousel-example-generic" role="button" 
    span.glyphicon.glyphicon-chevron-right aria-hidden="true" 
    span.sr-only Next

app/views/layouts/_services.html.slim
.container
  .row
    .col-lg-12
      h2 Почему стоит выбрать компанию «Крыминфоком»? Смотрите сами:
  .row
    .col-lg-3
      .icons
        i.fa.fa-wifi aria-hidden="true"
      p= t('crimeainfocom.services.description.wireless')
    .col-lg-3
      .icons
        i.fa.fa-globe aria-hidden="true"
      p= t('crimeainfocom.services.description.corporation')
    .col-lg-3
      .icons
        i.fa.fa-briefcase aria-hidden="true"
      p= t('crimeainfocom.services.description.office')
    .col-lg-3
      .icons
        i.fa.fa-cogs aria-hidden="true"
      p= t('crimeainfocom.services.description.support')

app/views/layouts/application.html.slim
doctype html
html
  head
    title ООО Крыминфоком
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  body
    header
      = render 'layouts/header'
    section.hover
      = render 'layouts/hover'
    section.services
      = render 'layouts/services'
    section.wrapper
      .container
        .row
          .col-lg-4.news
            h3 Новости и события
            == yield
          .col-lg-4.about
            h3 О нас
            = image_tag("about.jpg")
            p
              | Компания «Крыминфоком» начала свою деятельность в июне 1996 года. Уже много лет «Крыминфоком» успешно эксплуатирует одну из наибольших сетей передачи данных Республики Крым.
            p
              | Корпоративные сети, которые строит «Крыминфоком», дают возможность с большой эффективностью использовать каналы связи – передача данных, голосовая и видео передача одновременно, без дополнительных капиталовложений в телекоммуникационную инфраструктуру.
            P
              | «Крыминфоком» предлагает надежную техническую поддержку корпоративной сети на базе собственной мультисервисной телекоммуникационной сети.
          .col-lg-4.contacts
            .box
              h3 Абонентский отдел
              hr
              .box-line
                p
                  | Россия, Республика Крым, 
                  br/
                  | г. Cимферополь, ул. Тургенева, 20
                  br/
                ul
                  li 
                    i.fa.fa-phone aria-hidden="true"
                    span +7(3652) 24-85-25
                  li
                    i.fa.fa-phone aria-hidden="true"  
                    span +7(3652) 24-84-54
                  li
                    i.fa.fa-phone aria-hidden="true"
                    span +7(978) 838-37-23 (Win mobile)
                  li
                    i.fa.fa-phone aria-hidden="true"
                    span +7(978) 838-37-75 
                    = fa_icon "telegram", text: "(Win mobile)", class: "blue"
              .box-line 
                p
                  | Режим работы:
                  br/
                  | пн-пт 08:00 - 17:00
                  br/
                  i.fa.fa-envelope-o aria-hidden="true"
                  = mail_to("contacts@crimeainfo.com")
            .box
              h3 Техническая поддержка
              hr
              .box-line
                ul
                  li
                    i.fa.fa-phone aria-hidden="true"
                    span +7(3652) 54-70-77
                  li
                    i.fa.fa-phone aria-hidden="true"
                    span +7(978) 838-37-73 
                    = fa_icon "telegram", text: "(Win mobile)", class: "blue"
              .box-line
                p 
                  | Режим работы:
                  br/
                  | пн-пт 08:00 - 17:00
                  br/
                  | cуб 09:00 - 16:00
                  br/
                  | вск 09:00 - 11:30
                  br/
                  i.fa.fa-envelope-o aria-hidden="true"
                  = mail_to("support@crimeainfo.com")
    footer
      = render 'layouts/footer'

app/views/layouts/blog.html.slim
doctype html
html
  head
    title ООО Крыминфоком
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  body
    header
      = render 'layouts/header'
    section.wrapp-blue
      .container
        .row
          .col-lg-12
    section.content
      .container
        .row
          .col-lg-8.col-lg-offset-2
            == yield

    footer
      = render 'layouts/footer'